add teleport 🌀
diogocaronte/magnitude pull request #3
Opened 2024-08-13 19:05 UTC by evitarafadiga

nego brinca

2024-08-13 19:21 UTC, Felipeness approved these changes

2024-08-13 19:21 UTC, Felipeness commented
Se tem erro eu não vi

2024-08-13 19:34 UTC, diogocaronte requested changes

2024-08-13 19:34 UTC, diogocaronte commented on src/assets/circle/index.ts
> +};
caso for usar o circulo como placeholder
identificar como portal no enum

2024-08-13 19:34 UTC, diogocaronte commented on src/components/portal.ts
> +}
o componente apenas deve ter dados (comportamentos são nos sistemas)
o método de adição adiciona o componente portal então deve ser chamado de addPortal
o método de adição deve receber apenas as propriedades que será usada no componente


```suggestion
import { addComponent, defineComponent, IWorld, Types } from 'bitecs';

export const Portal = defineComponent({
    x: Types.f32,
    y: Types.f32,
});

export function addPortal(world: IWorld, entity: number, x: number, y: number) {
    addComponent(world, Portal, entity);
    Portal.x[entity] = x;
    Portal.y[entity] = y;
}

```

2024-08-13 19:35 UTC, diogocaronte commented on src/assets/circle/index.ts
> +};
não tem problema criar mais cores, é apenas uma sugestão.
Você pode resolver aqui sem mudar para portal

2024-08-17 18:08 UTC, evitarafadiga commented on src/assets/circle/index.ts
> +};
feito

2024-08-17 18:09 UTC, evitarafadiga commented on src/components/portal.ts
> +}
capicce

2024-08-17 22:45 UTC, diogocaronte approved these changes

2024-08-17 22:45 UTC, merged