Feature/planet
diogocaronte/magnitude pull request #8
Opened 2024-08-19 15:15 UTC by evitarafadiga

planet (por enquanto) não tem health como foi acordado tempos atrás

2024-08-21 14:13 UTC, diogocaronte requested changes

2024-08-21 14:13 UTC, diogocaronte commented on src/components/asteroid.ts
Esse componente não tem motivos para existir, podemos usar o componente de posição

2024-08-21 14:13 UTC, diogocaronte commented on src/components/asteroid/collision.ts
Por enquanto não precisamos diferenciar a colisão

2024-08-21 14:13 UTC, diogocaronte commented on src/components/enemy.ts
Esse componente não tem motivos para existir, podemos usar o componente de posição

2024-08-21 14:13 UTC, diogocaronte commented on src/components/enemy/collision.ts
Por enquanto não precisamos diferenciar a colisão

2024-08-21 14:13 UTC, diogocaronte commented on src/components/planet/collision.ts
Por enquanto não precisamos diferenciar a colisão

2024-08-21 14:13 UTC, diogocaronte commented on src/components/planet.ts
Esse componente não tem motivos para existir, podemos usar o componente de posição

2024-08-21 14:13 UTC, diogocaronte commented on src/entities/asteroid/index.ts
> +    addAsteroid(world, entity, x, y);
esse componente não existe mais
```suggestion
```

2024-08-21 14:13 UTC, diogocaronte commented on src/entities/enemy/index.ts
> +    addEnemy(world, entity, x, y);
esse componente não existe mais
```suggestion
```

2024-08-21 14:13 UTC, diogocaronte commented on src/entities/planet/index.ts
> +    addPlanet(world, entity, x, y);
esse componente não existe mais
```suggestion
```

2024-08-22 19:41 UTC, evitarafadiga commented
components excluded

2024-08-22 22:31 UTC, diogocaronte approved these changes

2024-08-22 22:31 UTC, merged